version: "3.8"

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile_master
    networks:
      - numeroPI

  nodo:
    build:
      context: .
      dockerfile: Dockerfile_nodo
    networks:
      - numeroPI

networks:
  numeroPI:
    driver: bridge
